import {create} from 'zustand'; import {workflows as seed} from '../../mock-data/workflows'; import {instances} from '../../mock-data/instances'; import type {Candidate,FlowEdge,FlowNode,MappingEntry,PromoteConflict,ValidationIssue,Workflow} from '../types'; import {graphHash,placeholderApprovers,validateGraph} from '../utils/graph';
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const now=()=>{const d=new Date(),p=(x:number)=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`};
const validate=(w:Workflow):ValidationIssue[]=>validateGraph(w.nodes,w.edges);
// 正式环境当前图哈希：未晋升过为空基线，否则取晋升版本快照
const prodHash=(w:Workflow):string=>{if(!w.prodVersion)return 'empty';const v=w.versions.find(x=>x.version===w.prodVersion);return v?graphHash(v.nodes,v.edges):'empty'};
interface State{workflows:Workflow[];instances:typeof instances;currentId:string;selectedNodeId:string|null;issues:ValidationIssue[];toast:string;setCurrent:(id:string)=>void;selectNode:(id:string|null)=>void;updateNodes:(nodes:FlowNode[])=>void;updateEdges:(edges:FlowEdge[])=>void;updateConfig:(id:string,config:Record<string,any>)=>void;runValidation:()=>ValidationIssue[];save:()=>void;publish:()=>void;create:()=>string;copy:(id:string)=>void;archive:(id:string)=>void;restore:(v:number)=>void;freezeCandidate:()=>ValidationIssue[];promote:(candidateId:string,mapping:Record<string,string>,fieldPlan:Record<string,'keep'|'remove'>)=>{ok:boolean;conflicts:PromoteConflict[]};clearToast:()=>void}
export const useAppStore=create<State>((set,get)=>({workflows:clone(seed),instances,currentId:'wf-1',selectedNodeId:null,issues:[],toast:'',setCurrent:id=>set({currentId:id,selectedNodeId:null,issues:[]}),selectNode:id=>set({selectedNodeId:id}),updateNodes:nodes=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes}:w)})),updateEdges:edges=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,edges}:w)})),updateConfig:(id,config)=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes:w.nodes.map(n=>n.id===id?{...n,data:{...n.data,config:{...n.data.config,...config},state:'configuring'}}:n)}:w)})),runValidation:()=>{const w=get().workflows.find(x=>x.id===get().currentId)!; const issues=validate(w); set(s=>({issues,workflows:s.workflows.map(x=>x.id===w.id?{...x,nodes:x.nodes.map(n=>({...n,data:{...n.data,state:issues.some(i=>i.nodeId===n.id)?'invalid':'valid'}}))}:x),toast:issues.length?`发现 ${issues.length} 个问题`:'校验通过'}));return issues},save:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'draft',updatedAt:now()}:w),toast:'草稿已保存'})),publish:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'published',version:w.version+1,publishedAt:now(),updatedAt:now(),versions:[...w.versions,{version:w.version+1,createdAt:now(),note:'发布最新审批配置',nodes:clone(w.nodes),edges:clone(w.edges)}]}:w),toast:'流程发布成功'})),create:()=>{const id='wf-'+Date.now();set(s=>({workflows:[{id,name:'未命名流程',domain:'财务',status:'draft',version:0,editor:'林秋',updatedAt:now(),abnormalCount:0,nodes:[],edges:[],versions:[],candidates:[],promotions:[]},...s.workflows],currentId:id}));return id},copy:id=>set(s=>{const w=s.workflows.find(x=>x.id===id)!;return{workflows:[{...clone(w),id:'wf-'+Date.now(),name:w.name+'（副本）',status:'draft'},...s.workflows]}}),archive:id=>set(s=>({workflows:s.workflows.map(w=>w.id===id?{...w,status:'archived'}:w)})),restore:v=>set(s=>({workflows:s.workflows.map(w=>{if(w.id!==s.currentId)return w;const old=w.versions.find(x=>x.version===v)!;return{...w,status:'draft',nodes:clone(old.nodes),edges:clone(old.edges)}}),toast:`已恢复 v${v} 为草稿`})),
// 冻结候选：测试版校验通过后快照，记录当前正式基线，供晋升比对
freezeCandidate:()=>{const w=get().workflows.find(x=>x.id===get().currentId)!;const issues=validate(w);if(issues.some(i=>i.level==='error')){set(s=>({issues,workflows:s.workflows.map(x=>x.id===w.id?{...x,nodes:x.nodes.map(n=>({...n,data:{...n.data,state:issues.some(i=>i.nodeId===n.id)?'invalid':'valid'}}))}:x),toast:`校验未过，无法冻结候选：${issues.filter(i=>i.level==='error').length} 个错误`}));return issues}const version=(w.candidates.at(-1)?.version||0)+1;const cand:Candidate={id:'cand-'+Date.now(),version,createdAt:now(),note:'测试版冻结为候选',hash:graphHash(w.nodes,w.edges),baselineHash:prodHash(w),nodes:clone(w.nodes),edges:clone(w.edges)};set(s=>({issues:[],workflows:s.workflows.map(x=>x.id===w.id?{...x,candidates:[...x.candidates,cand]}:x),toast:`已冻结候选 v${version}`}));return []},
// 环境晋升：校验候选、比对正式基线、映射占位审批人、处置试验字段；任一不满足则停住并列出冲突
promote:(candidateId,mapping,fieldPlan)=>{const w=get().workflows.find(x=>x.id===get().currentId)!;const cand=w.candidates.find(c=>c.id===candidateId);if(!cand)return{ok:false,conflicts:[{nodeId:'flow',nodeLabel:'候选版本',message:'候选版本不存在'}]};const conflicts:PromoteConflict[]=[];const label=(id:string)=>cand.nodes.find(n=>n.id===id)?.data.label||'流程';
 validateGraph(cand.nodes,cand.edges).filter(i=>i.level==='error').forEach(i=>conflicts.push({nodeId:i.nodeId,nodeLabel:label(i.nodeId),message:`校验未过：${i.message}`}));
 if(prodHash(w)!==cand.baselineHash)conflicts.push({nodeId:'flow',nodeLabel:'正式基线',message:'正式环境在候选冻结后已变化，请重新冻结候选'});
 placeholderApprovers(cand.nodes).forEach(({node,placeholder})=>{if(!mapping[node.id])conflicts.push({nodeId:node.id,nodeLabel:node.data.label,message:`占位审批人「${placeholder}」未映射正式人员`})});
 if(conflicts.length){set({toast:`晋升已阻止：${conflicts.length} 个冲突待解决`});return{ok:false,conflicts}}
 const nodes=clone(cand.nodes);placeholderApprovers(nodes).forEach(({node})=>{node.data.config.approver=mapping[node.id]});nodes.filter(n=>n.type==='form').forEach(n=>{n.data.config.fields=(n.data.config.fields||[]).filter((f:any)=>!f.experimental||fieldPlan[f.id]==='keep')});
 const entries:MappingEntry[]=placeholderApprovers(cand.nodes).map(({node,placeholder})=>({nodeId:node.id,placeholder,target:mapping[node.id]}));const toVersion=w.version+1,at=now();
 set(s=>({workflows:s.workflows.map(x=>x.id===w.id?{...x,status:'published',version:toVersion,prodVersion:toVersion,publishedAt:at,updatedAt:at,versions:[...x.versions,{version:toVersion,createdAt:at,note:`环境晋升自候选 v${cand.version}`,source:`候选 v${cand.version}`,mapping:entries,promotedAt:at,nodes:clone(nodes),edges:clone(cand.edges)}],promotions:[...x.promotions,{id:'promo-'+Date.now(),candidateVersion:cand.version,toVersion,promotedAt:at,mapping:entries,note:cand.note}]}:x),toast:`候选 v${cand.version} 已晋升为正式 v${toVersion}`}));
 return{ok:true,conflicts:[]}},
clearToast:()=>set({toast:''})}));
export {prodHash};
