import {test,expect} from '@playwright/test';
test.describe.serial('FlowDesk 完整链路',()=>{
 test('Dashboard KPI 与最近流程进入编辑器',async({page})=>{await page.goto('/');await expect(page.getByTestId('kpi-grid')).toBeVisible();await expect(page.getByText('流程总数')).toBeVisible();await expect(page.getByText('异常实例',{exact:true}).first()).toBeVisible();await page.getByTestId('recent-workflow').first().click();await expect(page.getByTestId('flow-canvas')).toBeVisible();});
 test('审批配置、保存和双区域校验',async({page})=>{await page.goto('/workflows/wf-1');await page.getByTestId('canvas-node-approval').click();await expect(page.getByTestId('config-panel')).toContainText('审批配置');await page.getByLabel('审批人来源').selectOption({label:'固定角色'});await page.getByTestId('save-node-config').click();await page.getByRole('button',{name:'保存草稿'}).click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/invalid/);await expect(page.getByTestId('issues-panel')).toContainText('条件分支规则未配置');const before=await page.getByTestId('error-count').textContent();expect(Number(before?.match(/\d+/)?.[0])).toBeGreaterThan(0);await page.getByTestId('canvas-node-condition').click();await page.getByLabel('条件字段').selectOption('amount');await page.getByLabel('条件比较值').fill('5000');await page.getByTestId('save-node-config').click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('error-count')).toContainText('0 错误');});
 test('表单预览金额驱动条件分支',async({page})=>{await page.goto('/workflows/wf-1/preview');await expect(page.getByTestId('branch-result')).toContainText('标准分支');await page.getByLabel('申请金额').fill('12000');await expect(page.getByTestId('branch-result')).toContainText('高额分支');});
 test('发布后列表和总览同步',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发布成功');await page.getByRole('link',{name:'流程管理'}).click();const row=page.getByTestId('workflow-row').filter({hasText:'采购合同审批'});await expect(row).toContainText('已发布');await expect(row).toContainText('v3');await page.getByRole('link',{name:'总览'}).click();await expect(page.getByTestId('kpi-grid')).toBeVisible();});
 test('异常实例详情、时间线与当前节点高亮',async({page})=>{await page.goto('/monitor');await page.getByRole('button',{name:'异常',exact:true}).click();await page.getByTestId('instance-row').first().click();await expect(page.getByTestId('instance-detail')).toBeVisible();await expect(page.getByTestId('execution-timeline')).toContainText('提交申请');await expect(page.locator('.runtime-highlight')).toHaveCount(1);});
 test('版本比较并恢复历史版本',async({page})=>{await page.goto('/workflows/wf-2/versions');await expect(page.getByTestId('version-compare')).toContainText('新增节点');await page.getByTestId('restore-version').click();await expect(page).toHaveURL(/\/workflows\/wf-2$/);await expect(page.getByRole('status')).toContainText('已恢复');await expect(page.getByTestId('flow-canvas')).toBeVisible();});
 test('晋升门禁：缺映射与校验未过会停住并列出节点',async({page})=>{await page.goto('/workflows/wf-1/promote');await expect(page.getByTestId('promote-page')).toBeVisible();await expect(page.getByTestId('gate-validation')).toContainText('条件分支规则未配置');await expect(page.getByTestId('gate-validation')).toContainText('试验字段未清理：试验字段-环境标记');await expect(page.getByTestId('placeholder-row')).toContainText('测试账号-小测');await expect(page.getByTestId('gate-baseline')).toContainText('候选后未再变化');await expect(page.getByTestId('promote-button')).toBeDisabled();await page.getByLabel('映射目标-测试账号-小测').selectOption('陈默');await expect(page.getByTestId('gate-mapping')).toContainText('全部已映射');await expect(page.getByTestId('promote-button')).toBeDisabled();});
 test('晋升门禁：基线变化列出冲突并停住',async({page})=>{await page.goto('/workflows/wf-3/promote');await expect(page.getByTestId('gate-baseline')).toContainText('基线已变化');await expect(page.getByTestId('baseline-conflicts')).toContainText('正式版本在候选冻结后已变化');await expect(page.getByTestId('promote-button')).toBeDisabled();});
 test('冻结候选、映射占位审批人并晋升到正式环境',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-approval').click();await page.getByLabel('审批人来源').selectOption({label:'指定成员'});await page.getByLabel('审批成员').fill('测试账号A');await page.getByTestId('save-node-config').click();await page.getByTestId('freeze-candidate').click();await expect(page.getByRole('status')).toContainText('候选版本已冻结');await page.getByTestId('promote-entry').click();await expect(page.getByTestId('gate-validation')).toContainText('校验通过');await expect(page.getByTestId('placeholder-row')).toContainText('测试账号A');await page.getByLabel('映射目标-测试账号A').selectOption('陈默');await expect(page.getByTestId('promote-button')).toBeEnabled();await page.getByTestId('promote-button').click();await expect(page).toHaveURL(/\/workflows\/wf-2\/versions$/);await expect(page.getByRole('status')).toContainText('已晋升到正式环境：v3');await expect(page.getByTestId('promotion-info')).toContainText('测试账号A → 陈默');await expect(page.getByTestId('promotion-info')).toContainText('晋升时间');await expect(page.getByTestId('candidate-card')).toBeVisible();});
 test('正式申请只认晋升版本，测试申请走候选快照',async({page})=>{await page.goto('/workflows/wf-1/preview');await expect(page.getByTestId('source-tag')).toContainText('测试环境');await expect(page.getByTestId('source-tag')).toContainText('候选快照');await page.getByTestId('env-toggle').getByRole('button',{name:'正式申请'}).click();await expect(page.getByText('正式申请仅接受晋升版本')).toBeVisible();await expect(page.getByTestId('source-tag')).toHaveCount(0);await page.goto('/workflows/wf-2/preview');await expect(page.getByTestId('source-tag')).toContainText('正式环境');await expect(page.getByTestId('source-tag')).toContainText('v2');});
});

test('1440px 桌面视觉与控制台验证',async({page})=>{
 const errors:string[]=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 for(const path of ['/','/workflows/wf-1','/monitor']){await page.goto(path);await page.waitForTimeout(250);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow,`${path} 不应横向溢出`).toBeFalsy()}
 await page.goto('/'); await page.screenshot({path:'test-results/dashboard-1440.png',fullPage:true});
 expect(errors,'浏览器 console 不应出现 error').toEqual([]);
});
