import {useEffect,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {ArrowLeft,CheckCircle2,Fingerprint,GitCommitHorizontal,Rocket,Snowflake,UserCheck,XCircle} from 'lucide-react';import {Empty,PageTitle} from '../components/common';import {evaluatePromotion} from '../lib/promotion';import {roles,users} from '../../mock-data/catalog';import {useAppStore} from '../store/useAppStore';
export function Promote(){const {id}=useParams(),nav=useNavigate();const store=useAppStore();const w=store.workflows.find(x=>x.id===id)||store.workflows[0];const [mapping,setMapping]=useState<Record<string,string>>({});useEffect(()=>{if(id&&id!==store.currentId)store.setCurrent(id)},[id]);const gate=evaluatePromotion(w);
 if(!w.candidate||!gate)return <div className="page"><button className="back-link" onClick={()=>nav(`/workflows/${w.id}`)}><ArrowLeft/>返回编辑器</button><PageTitle eyebrow="环境晋升" title="Environment Promotion" desc={`${w.name} · 将测试候选版本晋升到正式环境。`}/><Empty title="尚未冻结候选版本" text="请先在编辑器中将测试版冻结为候选版本，再发起环境晋升。"/><div className="promote-empty-action"><button onClick={()=>nav(`/workflows/${w.id}`)}><Snowflake/>去编辑器冻结候选</button></div></div>;
 const c=w.candidate,unmapped=gate.placeholders.filter(p=>!mapping[p.nodeId]),can=!gate.issues.length&&!unmapped.length&&gate.baseline.ok;
 const doPromote=()=>{if(store.promote(w.id,mapping))nav(`/workflows/${w.id}/versions`)};
 const blocked=[gate.issues.length&&`${gate.issues.length} 项校验未通过`,unmapped.length&&`${unmapped.length} 个占位审批人缺少映射`,!gate.baseline.ok&&'基线已变化'].filter(Boolean).join(' · ');
 return <div className="page"><button className="back-link" onClick={()=>nav(`/workflows/${w.id}`)}><ArrowLeft/>返回编辑器</button><PageTitle eyebrow="环境晋升" title="Environment Promotion" desc={`${w.name} · 候选版本冻结后需通过全部检查，占位审批人映射为正式人员方可晋升。`}/><div className="promote-layout" data-testid="promote-page">
 <aside className="panel candidate-panel"><h3><Snowflake/>候选版本</h3><div className="candidate-meta"><div><small>冻结时间</small><b>{c.frozenAt}</b></div><div><small>快照指纹</small><b className="hash"><Fingerprint/>{c.hash}</b></div><div><small>正式基线</small><b>{c.baseVersion?`v${c.baseVersion}`:'无正式版本'}</b></div><div><small>规模</small><b>{c.nodes.length} 节点 · {c.edges.length} 连线</b></div></div><p className="candidate-note">{c.note}：测试申请继续使用该快照，晋升不影响测试环境。</p></aside>
 <section className="panel gates"><h3><GitCommitHorizontal/>晋升检查</h3>
 <div className={'gate '+(gate.issues.length?'blocked':'ok')} data-testid="gate-validation"><div className="gate-head">{gate.issues.length?<XCircle/>:<CheckCircle2/>}<b>候选快照校验</b><span>{gate.issues.length?`${gate.issues.length} 个问题`:'校验通过'}</span></div>{gate.issues.length>0&&<ul>{gate.issues.map((i,k)=><li key={k}><b>{i.nodeLabel}</b><span>{i.message}</span></li>)}</ul>}</div>
 <div className={'gate '+(unmapped.length?'blocked':'ok')} data-testid="gate-mapping"><div className="gate-head">{unmapped.length?<XCircle/>:<CheckCircle2/>}<b>占位审批人映射</b><span>{gate.placeholders.length?(unmapped.length?`还差 ${unmapped.length} 项`:'全部已映射'):'无占位审批人'}</span></div>{gate.placeholders.map(p=><div className="mapping-row" data-testid="placeholder-row" key={p.nodeId}><UserCheck/><div className="mapping-info"><b>{p.nodeLabel}</b><small>{p.kind==='member'?'占位成员':'占位角色'}：{p.value}</small></div><select aria-label={`映射目标-${p.value}`} value={mapping[p.nodeId]||''} onChange={e=>setMapping({...mapping,[p.nodeId]:e.target.value})}><option value="">请选择正式{p.kind==='member'?'人员':'角色'}</option>{(p.kind==='member'?users:roles).map(x=><option key={x} value={x}>{x}</option>)}</select></div>)}</div>
 <div className={'gate '+(gate.baseline.ok?'ok':'blocked')} data-testid="gate-baseline"><div className="gate-head">{gate.baseline.ok?<CheckCircle2/>:<XCircle/>}<b>基线一致性</b><span>{gate.baseline.ok?'候选后未再变化':'基线已变化'}</span></div>{gate.baseline.ok?<p className="gate-tip">草稿与正式版本自候选冻结后保持一致。</p>:<div data-testid="baseline-conflicts"><ul>{gate.baseline.conflicts.map((x,k)=><li key={k}><span>{x}</span></li>)}</ul>{[['新增',gate.baseline.diff.added],['删除',gate.baseline.diff.removed],['变更',gate.baseline.diff.changed]].map(([t,list]:any)=>list.length>0&&<div className="conflict-nodes" key={t}><small>{t}节点</small>{list.map((l:string)=><em key={l}>{l}</em>)}</div>)}</div>}</div>
 <div className="promote-footer"><span>{can?`全部检查通过，晋升后将生成正式版本 v${w.version+1}`:`晋升已停住：${blocked}`}</span><button data-testid="promote-button" disabled={!can} onClick={doPromote}><Rocket/>晋升到正式环境</button></div>
 </section></div></div>}
