import {useEffect,useMemo,useState} from 'react'; import {useNavigate,useParams} from 'react-router-dom'; import {ArrowLeft,CheckCircle2,FlaskConical,History,Rocket,Server,Snowflake,XCircle} from 'lucide-react'; import {Empty,PageTitle} from '../components/common'; import {prodHash,useAppStore} from '../store/useAppStore'; import {experimentalFields,placeholderApprovers,validateGraph} from '../utils/graph'; import {users} from '../../mock-data/catalog'; import type {PromoteConflict} from '../types';
export function Promote(){const {id}=useParams(),nav=useNavigate(),store=useAppStore(),w=store.workflows.find(x=>x.id===id)||store.workflows[0];useEffect(()=>{if(id&&id!==store.currentId)store.setCurrent(id)},[id]);const [sel,setSel]=useState<string|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[fieldPlan,setFieldPlan]=useState<Record<string,'keep'|'remove'>>({});const cand=w.candidates.find(c=>c.id===sel)||w.candidates.at(-1)||null;const prodV=w.prodVersion?w.versions.find(v=>v.version===w.prodVersion):undefined;
 const placeholders=useMemo(()=>cand?placeholderApprovers(cand.nodes):[],[cand]),expFields=useMemo(()=>cand?experimentalFields(cand.nodes):[],[cand]),baselineOk=!!cand&&prodHash(w)===cand.baselineHash,validation=useMemo(()=>cand?validateGraph(cand.nodes,cand.edges).filter(i=>i.level==='error'):[],[cand]);
 const live=useMemo(()=>{if(!cand)return[];const c:PromoteConflict[]=[];const label=(nid:string)=>cand.nodes.find(n=>n.id===nid)?.data.label||'流程';validation.forEach(i=>c.push({nodeId:i.nodeId,nodeLabel:label(i.nodeId),message:`校验未过：${i.message}`}));if(!baselineOk)c.push({nodeId:'flow',nodeLabel:'正式基线',message:'正式环境在候选冻结后已变化，请重新冻结候选'});placeholders.forEach(({node,placeholder})=>{if(!mapping[node.id])c.push({nodeId:node.id,nodeLabel:node.data.label,message:`占位审批人「${placeholder}」未映射正式人员`})});return c},[cand,validation,baselineOk,placeholders,mapping]);
 const conflicts=live;
 const freeze=()=>{const issues=store.freezeCandidate();if(!issues.length){const latest=useAppStore.getState().workflows.find(x=>x.id===w.id)?.candidates.at(-1);if(latest)setSel(latest.id)}};
 const doPromote=()=>{if(!cand)return;const r=store.promote(cand.id,mapping,fieldPlan);if(r.ok){setMapping({});setFieldPlan({})}};
 return <div className="page promote-page"><button className="back-link" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/>返回编辑器</button><PageTitle eyebrow="环境晋升" title="Environment Promotion" desc={`${w.name} · 测试版冻结为候选，校验、映射与基线确认后晋升为正式版本。`}/>
 <div className="env-track"><section className="panel env-card"><small><FlaskConical/>测试环境</small><b>v{w.version} · {w.status==='draft'?'草稿':'已发布'}</b><p>最近更新 {w.updatedAt}</p><button data-testid="freeze-button" onClick={freeze}><Snowflake/>冻结为候选版本</button></section><span className="env-arrow">→</span><section className="panel env-card"><small><History/>候选版本</small><b>{w.candidates.length} 个候选</b><p>{cand?`最新候选 v${cand.version} · ${cand.createdAt}`:'尚未冻结候选'}</p></section><span className="env-arrow">→</span><section className="panel env-card" data-testid="prod-env"><small><Server/>正式环境</small><b>{prodV?`v${prodV.version} · 已晋升`:'未晋升'}</b><p>{prodV?`${prodV.source} · 晋升于 ${prodV.promotedAt}`:'正式申请只认晋升版本'}</p></section></div>
 <div className="promote-layout"><aside className="panel candidate-list"><h3><Snowflake/>候选快照</h3>{w.candidates.length?[...w.candidates].reverse().map(c=>{const errs=validateGraph(c.nodes,c.edges).filter(i=>i.level==='error').length,ph=placeholderApprovers(c.nodes).length,exp=experimentalFields(c.nodes).length,stale=prodHash(w)!==c.baselineHash;return <button key={c.id} data-testid="candidate-card" className={c.id===(cand?.id||sel)?'active':''} onClick={()=>{setSel(c.id)}}><span><b>候选 v{c.version}</b>{stale?<em className="stale">基线已变化</em>:<em>基线一致</em>}</span><small>{c.createdAt} · 指纹 {c.hash.slice(0,8)}</small><p>{c.note}</p><small>{errs?`${errs} 个校验错误 · `:''}{ph?`${ph} 个占位审批人 · `:''}{exp?`${exp} 个试验字段`:''}{!errs&&!ph&&!exp?'无待处理项':''}</small></button>}):<Empty title="尚未冻结候选" text="在测试环境校验通过后，将当前测试版冻结为候选快照"/>}</aside>
 <section className="panel promote-panel">{cand?<><div className="panel-head"><div><h2>晋升检查 · 候选 v{cand.version}</h2><p>缺映射、校验未过或基线变化将阻止晋升</p></div><button data-testid="promote-button" onClick={doPromote}><Rocket/>晋升到正式环境</button></div>
 <div className="check-list"><div className={validation.length?'check fail':'check pass'}>{validation.length?<XCircle/>:<CheckCircle2/>}<div><b>结构校验</b><small>{validation.length?`${validation.length} 个错误`:'候选快照校验通过'}</small></div></div><div className={baselineOk?'check pass':'check fail'}>{baselineOk?<CheckCircle2/>:<XCircle/>}<div><b>正式基线</b><small>{baselineOk?'正式环境自候选冻结后未变化':'正式环境已变化，需重新冻结候选'}</small></div></div><div className={placeholders.every(p=>mapping[p.node.id])?'check pass':'check fail'}>{placeholders.every(p=>mapping[p.node.id])?<CheckCircle2/>:<XCircle/>}<div><b>占位审批人映射</b><small>{placeholders.length?`${placeholders.filter(p=>mapping[p.node.id]).length}/${placeholders.length} 已映射`:'无占位审批人'}</small></div></div></div>
 {placeholders.length>0&&<div className="mapping-block"><h4>占位审批人 → 正式人员</h4>{placeholders.map(({node,placeholder})=><label key={node.id} className="mapping-row"><span><b>{node.data.label}</b><em>{placeholder}</em></span><select aria-label={`正式人员-${node.id}`} value={mapping[node.id]||''} onChange={e=>setMapping({...mapping,[node.id]:e.target.value})}><option value="">请选择正式人员</option>{users.map(u=><option key={u}>{u}</option>)}</select></label>)}</div>}
 {expFields.length>0&&<div className="mapping-block"><h4>试验字段处置</h4>{expFields.map(({node,field})=><label key={field.id} className="mapping-row"><span><b>{field.label}</b><em>来自「{node.data.label}」· 默认不进入正式申请</em></span><select aria-label={`试验字段-${field.id}`} value={fieldPlan[field.id]||'remove'} onChange={e=>setFieldPlan({...fieldPlan,[field.id]:e.target.value as 'keep'|'remove'})}><option value="remove">晋升时移除</option><option value="keep">保留到正式</option></select></label>)}</div>}
 {conflicts.length>0&&<div className="conflict-list" data-testid="promote-conflicts"><h4><XCircle/>晋升已停住 · {conflicts.length} 个冲突</h4>{conflicts.map((c,i)=><div key={c.nodeId+i} className="conflict"><b>{c.nodeLabel}</b><span>{c.message}</span><small>节点：{c.nodeId}</small></div>)}</div>}
 </>:<Empty title="选择候选版本" text="先冻结候选快照，再执行晋升检查"/>}</section></div>
 <section className="panel promotion-history" data-testid="promotion-history"><div className="panel-head"><div><h2>晋升历史</h2><p>来源、映射与晋升时间全量留痕</p></div></div>{w.promotions.length?<table><thead><tr><th>来源</th><th>正式版本</th><th>占位映射</th><th>晋升时间</th><th>说明</th></tr></thead><tbody>{[...w.promotions].reverse().map(p=><tr key={p.id}><td>候选 v{p.candidateVersion}</td><td><b>v{p.toVersion}</b></td><td>{p.mapping.length?p.mapping.map(m=><span key={m.nodeId} className="map-chip">{m.placeholder} → {m.target}</span>):'—'}</td><td>{p.promotedAt}</td><td>{p.note}</td></tr>)}</tbody></table>:<Empty title="暂无晋升记录"/>}</section></div>}
