import type {Candidate,FlowEdge,FlowNode,Workflow} from '../src/types';
import {graphHash} from '../src/utils/graph';
const n=(id:string,type:FlowNode['type'],x:number,y:number,label:string,config:Record<string,any>={}):FlowNode=>({id,type,position:{x,y},data:{label,state:Object.keys(config).length?'valid':'unconfigured',config}});
const standard=(broken=false)=>{
 const nodes=[n('start','start',20,150,'开始',{ok:true}),n('form','form',210,150,'提交申请',{fields:[{id:'reason',label:'申请说明',type:'text',required:true},{id:'amount',label:'申请金额',type:'amount',required:true},{id:'attachment',label:'附件',type:'attachment',required:false}]}),n('approval','approval',420,150,'直属主管审批',{approverSource:'直属主管',instruction:'请确认申请内容与预算归属'}),n('condition','condition',630,150,'金额判断',broken?{}:{ruleType:'amount',operator:'>',value:5000}),n('notify','notify',850,40,'高额通知',{targets:'财务审批人',template:'高额申请提醒',timing:'分支进入时'}),n('automation','automation',850,260,'记录系统',{action:'写入系统记录'}),n('end','end',1070,150,'结束',{ok:true})];
 const edges:FlowEdge[]=[['start','form'],['form','approval'],['approval','condition'],['condition','notify','大于 5,000'],['condition','automation','其他'],['notify','end'],['automation','end']].map((e,i)=>({id:'e'+i,source:e[0],target:e[1],label:e[2]})); return {nodes,edges};
};
const names=['差旅费用审批','采购合同审批','员工入职流程','IT 服务请求','用印申请','供应商准入','年度预算调整','客户退款审批','法务审查流程','资产领用审批','营销活动报备','跨区域大型采购及多部门联合审批流程（集团特别管控版）'];
export const workflows:Workflow[]=names.map((name,i)=>{const graph=i===10?{nodes:[],edges:[]}:standard(i===0||i===3); if(i===8) graph.nodes=graph.nodes.filter(x=>x.type!=='end'); if(i===9) graph.nodes.push(n('orphan','approval',650,390,'孤立审批',{}));
 // wf-2：测试版含占位审批人与试验字段，并已冻结一条候选
 if(i===1){graph.nodes=graph.nodes.map(x=>x.id==='approval'?{...x,data:{...x.data,config:{...x.data.config,approverSource:'指定成员',approver:'占位·张冠'}}}:x);const form=graph.nodes.find(x=>x.id==='form')!;form.data.config.fields=[...form.data.config.fields,{id:'costCenter',label:'成本中心（试验）',type:'text',required:false,experimental:true}]}
 const status=i%4===0?'draft':i%5===0?'archived':'published'; const oldNodes=graph.nodes.filter(x=>x.id!=='notify').map(x=>({...x,data:{...x.data}}));
 const candidates:Candidate[]=i===1?[{id:'cand-seed-1',version:1,createdAt:'2026-07-09 11:20',note:'采购合同测试版冻结',hash:graphHash(graph.nodes,graph.edges),baselineHash:'empty',nodes:graph.nodes,edges:graph.edges}]:[];
 const promotions=i===2?[{id:'promo-seed-1',candidateVersion:1,toVersion:2,promotedAt:'2026-07-01 16:25',mapping:[{nodeId:'approval',placeholder:'占位·李代',target:'王宁'}],note:'入职流程首次晋升'}]:[];
 const versions=[{version:1,createdAt:'2026-06-12 10:00',note:'初始化流程结构',nodes:oldNodes,edges:graph.edges.filter(e=>e.source!=='notify'&&e.target!=='notify')},{version:2,createdAt:'2026-07-01 16:20',note:'增加金额分支与通知节点',nodes:graph.nodes,edges:graph.edges,...(i===2?{source:'候选 v1',mapping:[{nodeId:'approval',placeholder:'占位·李代',target:'王宁'}],promotedAt:'2026-07-01 16:25'}:{})}];
 return {id:'wf-'+(i+1),name,domain:['财务','采购','人力资源','IT服务','法务'][i%5],status,version:i%3+1,editor:['林秋','陈默','周礼','王宁'][i%4],updatedAt:`2026-07-${String(10-i%9).padStart(2,'0')} ${9+i%8}:20`,publishedAt:status==='published'?'2026-07-08 14:30':undefined,abnormalCount:i===7?0:i%4,nodes:graph.nodes,edges:graph.edges,versions,candidates,promotions,prodVersion:i===2?2:undefined};});
